spring.datasource.url=jdbc:postgresql://localhost:5432/beautydb
spring.datasource.username= postgres
spring.datasource.password= postgres


# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
#
spring.jpa.hibernate.ddl-auto = update

server.port=8014
spring.application.name=beautyIms-service
micro.file-service.name = file-service
micro.file-service.url =  http://localhost:8011
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.default-model-expand-depth=-1